# Generated by Django 4.2 on 2023-10-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
